### ISSUE TITLE
Display of a collection of books

### ISSUE THREAD

**Issue by NathalieScherf** [NathalieScherf/Reading-List-App#1]
User story: Who, what, why

"As a reader, I want to be able to see all my books in on app, to keep the overview of the collection"

**Tasks**
- [x] Set up 
- [x] Basic content (html, css, js files)
- [x] Use js to create one card
- [x] Think about the data (books)
- [x] Use js to create many cards

**Mockup:** 

![Image](https://github.com/NathalieScherf/Reading-List-App/assets/43681554/77868395-b04c-4fc3-824d-b29eef859a98)
